# Veri Bilimi için Python Kütüphaneleri

### - NumPy
### - Pandas
### - Matplotlib
### - Seaborn
### - Scikit-Learn

# NumPy

NumPy (Numerical Python), Python programlama dili için bir kütüphanedir ve bilimsel hesaplama ve veri işleme işlemlerinde kullanılır. NumPy, çok boyutlu (ndarray) dizileri, matematiksel işlemleri, rastgele sayı üretimi, lineer cebir, Fourier analizi ve diğer sayısal algoritmaları kolayca uygulama imkanı sağlar.

NumPy, bilimsel ve mühendislik alanlarında yaygın olarak kullanılmaktadır. Örneğin, veri analizi, görüntü işleme, yapay zeka, makine öğrenmesi, hesaplamalı fizik, matematik, istatistik, biyoinformatik ve diğer birçok alanda kullanılmaktadır. NumPy, açık kaynaklı bir yazılım olduğu için dünya genelinde birçok araştırmacı ve geliştirici tarafından kullanılır ve geliştirilir.

## 1. NumPy Temelleri
- NumPy'nin tanımlanması ve kurulumu
- NumPy dizileri (ndarray) oluşturma

## 2. Dizi İşlemleri
- Dizi şekilleri ve boyutları
- Dizi elemanlarına erişim ve değiştirme
- NumPy dizilerinde matematiksel işlemler (toplama, çıkarma, çarpma vb.)
- Dizi işlemleri: Dizileri birleştirme, dizileri bölmek, sıralama, filtreleme vb.
- Dizi işlemleri için uygulama örnekleri

## 3. Dizilerde İndeksleme ve Dilimleme
- Dizi elemanlarına erişim ve değiştirme
- İndeksleme ve dilimleme işlemlerinin uygulanması
- İndeksleme ve dilimleme için örnekler

## 4. Dizi Şekilleri ve Boyutları
- Dizi şekilleri ve boyutları
- Dizi şekillerinin değiştirilmesi
- Dizi boyutlarının değiştirilmesi
- Yığın (stacking) işlemleri

## 5. Dizi İşlemleri İçin Fonksiyonlar
- Dizi işlemleri için matematiksel fonksiyonlar (exp, log, sin, cos, vb.)
- Dizi işlemleri için istatistiksel fonksiyonlar (mean, median, std, var, vb.)
- Dizi işlemleri için diğer kullanışlı fonksiyonlar (where, any, all, argmax, argmin, vb.)

## 6. Dizilerde Dosya İşlemleri
- NumPy dizilerini dosyalara kaydetmek
- NumPy dizilerini dosyalardan yüklemek
- Dosya işlemleri için örnekler

## 7. Matris İşlemleri
- Matrislerin oluşturulması
- Matrislerin işlemleri (toplama, çıkarma, çarpma vb.)
- Matris işlemleri için örnekler

## 8. Broadcasting
- NumPy dizilerinde yayılma işlemi (broadcasting)
- Yayılma işlemi için örnekler

## 9. Genel İşlemler
- Dizi ve matris işlemlerinde performansı artırmak için NumPy kullanımı
- NumPy ile hızlı hesaplama örnekleri
- NumPy ve diğer Python kütüphaneleri arasındaki farklar

## 10. Makine Öğrenmesi için NumPy Kullanımı
- NumPy kullanımı ile veri işleme ve önişleme işlemleri
- NumPy kullanımı ile matris çarpımı ve doğrusal cebir işlemleri
- NumPy kullanımı ile veri analizi ve görselleştirme işlemleri
- NumPy kullanımı ile makine öğrenmesi algoritmalarının uygulanması (regresyon, sınıflandırma, kümeleme, boyut indirgeme, vb.)
- Makine öğrenmesi için NumPy ile veri manipülasyonu ve dönüştürme işlemleri.

## 1. NumPy Temelleri

### - NumPy'nin tanımlanması ve kurulumu

NumPy, standart Python dağıtımının bir parçası değildir. Ancak, NumPy, Python Anaconda dağıtımı gibi bazı Python dağıtımlarında varsayılan olarak yüklü olarak gelir. NumPy, birkaç farklı yöntemle kurulabilir.

**1. pip kullanarak:**
NumPy, pip aracılığıyla kolayca kurulabilir. Aşağıdaki komutu kullanarak NumPy'ı kurabilirsiniz:

- pip install numpy

**1. Conda kullanarak:**

Anaconda veya Miniconda gibi bir Python dağıtımı kullanıyorsanız, NumPy'nin zaten yüklü olduğundan emin olun. NumPy'yı yüklemek istiyorsanız, aşağıdaki komutu kullanabilirsiniz:

- conda install numpy

**3. Kaynak kodunu derleyerek:**

NumPy kaynak kodunu indirerek ve derleyerek de NumPy'ı kurabilirsiniz. NumPy'nin son sürümünü NumPy web sitesinden indirebilirsiniz.

İndirme işleminden sonra, dosyayı açın ve aşağıdaki komutları kullanarak NumPy'yı derleyin ve kurun:

- python setup.py build
- python setup.py install


NumPy, farklı platformlarda (Windows, macOS, Linux vb.) kullanılabilir ve kullanıcıların ihtiyaçlarına uygun bir şekilde yapılandırılabilir. Kurulum işlemi tamamlandıktan sonra, NumPy kullanıma hazır olacaktır.


### - NumPy dizileri (ndarray) oluşturma

NumPy'da ndarray (N-dimensional array) olarak adlandırılan, homojen veri tiplerine sahip çok boyutlu diziler kullanılır. Bu diziler, liste veya tuple gibi Python'un yerleşik veri tipleriyle benzerlik gösterse de, NumPy'nin sağladığı birçok avantajı da içerir.

NumPy ndarray'leri oluşturmak için birkaç yöntem vardır. Bunlardan en sık kullanılanları aşağıdaki gibidir:

**1. np.array():** Python listesini veya tuple'ı bir NumPy ndarray'ye dönüştürmek için kullanılır

In [12]:
import numpy as np

# Python listesini NumPy ndarray'ye dönüştürme
my_list = [1, 2, 3, 4, 5]
arr = np.array(my_list)

# NumPy ndarray'sinin boyutunu yazdırma
print(arr.shape)  # çıktı: (5,)

(5,)


**2. np.zeros():** Belirli bir boyutta sıfırlardan oluşan bir ndarray oluşturmak için kullanılır.

In [13]:
import numpy as np

# 3x4 boyutunda sıfırlardan oluşan bir NumPy ndarray'si oluşturma
zeros_arr = np.zeros((3, 4))

# NumPy ndarray'sinin boyutunu ve veri tipini yazdırma
print(zeros_arr.shape)  # çıktı: (3, 4)
print(zeros_arr.dtype)  # çıktı: float64

(3, 4)
float64


**3. np.ones():** Belirli bir boyutta birlerden oluşan bir ndarray oluşturmak için kullanılır.

In [14]:
import numpy as np

# 2x2 boyutunda birlerden oluşan bir NumPy ndarray'si oluşturma
ones_arr = np.ones((2, 2))

# NumPy ndarray'sinin boyutunu ve veri tipini yazdırma
print(ones_arr.shape)  # çıktı: (2, 2)
print(ones_arr.dtype)  # çıktı: float64

(2, 2)
float64


**4. np.arange():** Belirli bir aralıkta eşit aralıklarla sayılar içeren bir ndarray oluşturmak için kullanılır.

In [15]:
import numpy as np

# 0'dan 9'a kadar olan sayıları içeren bir NumPy ndarray'si oluşturma
range_arr = np.arange(10)

# NumPy ndarray'sinin boyutunu yazdırma
print(range_arr.shape)  # çıktı: (10,)

(10,)


**5. np.linspace():** Belirli bir aralıkta belirtilen sayıda eşit aralıklarla sayılar içeren bir ndarray oluşturmak için kullanılır.

In [18]:
import numpy as np

# 0 ile 1 arasında 5 adet sayı içeren bir NumPy ndarray'si oluşturma
linspace_arr = np.linspace(0, 1, 5)

# NumPy ndarray'sinin boyutunu yazdırma
print(linspace_arr.shape)  # çıktı: (5,)

(5,)


## 2. Dizi İşlemleri

### - Dizi şekilleri ve boyutları

NumPy dizileri (ndarrays) 1 boyutlu (vektörler) veya 2 boyutlu (matrisler) olabileceği gibi, 3 veya daha fazla boyutlu diziler de olabilir.

Dizi boyutları, şekli (shape) niteliği ile belirtilir. Örneğin, aşağıdaki kod ile 2 boyutlu bir (3,4) şeklinde bir dizi oluşturabiliriz:

In [24]:
import numpy as np

arr = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12]])

# Dizi boyutları, şekli (shape) niteliği ile belirtilir. 
# Bu çıktı olarak (3, 4) döndürecektir, yani bu dizi 3 satır ve 4 sütuna sahiptir.
print(arr.shape)

# Dizi boyutu, ndim niteliği ile belirtilir. 
# Bu çıktı olarak 2 döndürecektir, yani bu dizi 2 boyutludur.
print(arr.ndim)

# Bir dizi yeniden şekillendirilirken, verilerin sıralaması değiştirilmeden bir boyuttan diğerine yeniden düzenlenir.
# Bu çıktı olarak (4, 3) döndürecektir, yani bu dizi 4 satır ve 3 sütuna sahiptir.
arr2 = arr.reshape((4, 3))
print(arr2.shape)

# Bir dizi boyutu, size niteliği ile belirtilir ve toplam eleman sayısını verir.
print(arr.size)

(3, 4)
2
(4, 3)
12


### - Dizi elemanlarına erişim ve değiştirme

NumPy dizilerindeki elemanlara erişmek için dizinin indeksini kullanmak yeterlidir. Ayrıca, dizinin dilimleme özelliği de kullanılabilir. 

Not: NumPy dizileri, Python listelerinin aksine değiştirilebilir (mutable) nesnelerdir. Yani, dizinin elemanlarına erişip değiştirdikten sonra orijinal dizi değişir.

In [25]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

#Bu dizinin ilk elemanına erişmek için indeks 0 kullanılır:
print(arr[0]) # Output: 1

# Dizinin ikinci elemanına erişmek için indeks 1 kullanılır:
print(arr[1]) # Output: 2

# Dizinin son elemanına erişmek için negatif indeks kullanılabilir:
print(arr[-1]) # Output: 5

# Dizinin ikinci ve üçüncü elemanlarına erişmek için dilimleme kullanılabilir:
print(arr[1:3]) # Output: [2 3]

# Dizinin elemanlarını değiştirmek için de aynı indeksleme ve dilimleme kullanılabilir. 
# Örneğin, dizinin ilk elemanını 10 ile değiştirelim:
arr[0] = 10
print(arr) # Output: [10  2  3  4  5]

## Dizinin ikinci ve üçüncü elemanlarını 20 ve 30 ile değiştirelim:
arr[1:3] = [20, 30]
print(arr) # Output: [10 20 30  4  5]

1
2
5
[2 3]
[10  2  3  4  5]
[10 20 30  4  5]


### - NumPy dizilerinde matematiksel işlemler (toplama, çıkarma, çarpma vb.)

NumPy, dizi elemanları üzerinde matematiksel işlemler yapmak için bir dizi matematiksel fonksiyon sağlar.

In [33]:
import numpy as np

# Dizi oluştur
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

# Toplama
arr3 = arr1 + arr2
print("Toplam Dizisi:")
print(arr3)

# Çıkarma
arr4 = arr1 - arr2
print("Çıkarma Dizisi:")
print(arr4)

# Çarpma
arr5 = arr1 * arr2
print("Çarpım Dizisi:")
print(arr5)

# Bölme
arr6 = arr2 / arr1
print("Bölüm Dizisi:")
print(arr6)

# Karekök alma
arr7 = np.sqrt(arr1)
print("Karekök Dizisi:")
print(arr7)

Toplam Dizisi:
[5 7 9]
Çıkarma Dizisi:
[-3 -3 -3]
Çarpım Dizisi:
[ 4 10 18]
Bölüm Dizisi:
[4.  2.5 2. ]
Karekök Dizisi:
[1.         1.41421356 1.73205081]


### - Dizi işlemleri: Dizileri birleştirme, dizileri bölmek, sıralama, filtreleme vb.

- **Dizileri Birleştirme:**

NumPy, concatenate() fonksiyonu aracılığıyla bir veya daha fazla dizi birleştirmeye izin verir.

In [28]:
import numpy as np

# Dizileri oluştur
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6]])

# Dizileri birleştir
arr3 = np.concatenate((arr1, arr2), axis=0)
print("Birleştirilmiş Dizi:")
print(arr3)


Birleştirilmiş Dizi:
[[1 2]
 [3 4]
 [5 6]]


- **Dizileri Bölmek:**

NumPy, split() fonksiyonu ile bir diziyi iki veya daha fazla dizide bölmek için kullanılabilir.

In [29]:
import numpy as np

# Dizi oluştur
arr1 = np.array([1, 2, 3, 4, 5, 6])

# Diziyi bölmek
arr2, arr3, arr4 = np.split(arr1, [2, 4])
print("Bölünmüş Diziler:")
print(arr2)
print(arr3)
print(arr4)


Bölünmüş Diziler:
[1 2]
[3 4]
[5 6]


- **Sıralama:**

NumPy, sort() fonksiyonu ile bir dizi elemanlarını sıralamak için kullanılabilir.


In [32]:
import numpy as np

# Dizi oluştur
arr1 = np.array([3, 2, 0, 1, 5, 4])

# Diziyi sıralamak
arr2 = np.sort(arr1)
print("Sıralanmış Dizi:")
print(arr2)

# Bu dizinin elemanlarını ters sırayla almak için flip() fonksiyonunu kullanabiliriz:
arr3 = np.flip(arr1)
print("Tersten Sıralanmış Dizi:")
print(arr3)

Sıralanmış Dizi:
[0 1 2 3 4 5]
Tersten Sıralanmış Dizi:
[4 5 1 0 2 3]


- **Filtreleme:**

NumPy, dizi elemanlarını filtrelemek için kullanılabilen where() fonksiyonuna sahiptir.

In [31]:
import numpy as np

# Dizi oluştur
arr1 = np.array([1, 2, 3, 4, 5])

# Filtreleme
arr2 = np.where(arr1 > 3)
print("Filtrelenmiş Dizi:")
print(arr2)


Filtrelenmiş Dizi:
(array([3, 4], dtype=int64),)


### - Dizi işlemleri için uygulama örnekleri

- **Matematiksel işlemler**

NumPy dizilerinde matematiksel işlemler yapmak için NumPy matematik fonksiyonları kullanılabilir. Örneğin:

In [34]:
import numpy as np

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

# Toplama
c = a + b
print(c)  # Output: [5 7 9]

# Çıkarma
c = a - b
print(c)  # Output: [-3 -3 -3]

# Çarpma
c = a * b
print(c)  # Output: [ 4 10 18]

# Bölme
c = a / b
print(c)  # Output: [0.25 0.4  0.5 ]

# Kuvvet
c = np.power(a, b)
print(c)  # Output: [  1  32 729]


[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]
[  1  32 729]


- **Dizileri birleştirme**

NumPy'de dizileri birleştirmek için ***concatenate()*** veya ***stack()*** fonksiyonları kullanılabilir. Örneğin:

In [37]:
import numpy as np

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

# Birleştirme
c = np.concatenate((a, b))
print(c)  # Output: [1 2 3 4 5 6]

# Dizileri yatay olarak birleştirme
c = np.stack((a, b), axis=1)
print(c)  # Output: [[1 4] [2 5] [3 6]]

[1 2 3 4 5 6]
[[1 4]
 [2 5]
 [3 6]]


- **Dizileri bölmek***

NumPy'de bir dizi, belirtilen bir konumda bölünebilir. split() fonksiyonu, bir diziyi belirtilen konumda bölmenizi sağlar. Örneğin:

In [38]:
import numpy as np

a = np.array([1, 2, 3, 4, 5, 6])

# Diziyi 2. indexten böl
b, c = np.split(a, [2])

print(b)  # Output: [1 2]
print(c)  # Output: [3 4 5 6]


[1 2]
[3 4 5 6]


- **Sıralama ve filtreleme***

NumPy'de sıralama işlemi yapmak için sort() fonksiyonu kullanılabilir. Ayrıca, NumPy dizilerinde filtreleme işlemi yapmak için mantıksal diziler kullanabilirsiniz. Örneğin:

In [39]:
import numpy as np

a = np.array([3, 1, 4, 1, 5, 9, 2, 6, 5, 3, 5])

# Diziyi sırala
b = np.sort(a)
print(b)  # Output: [1 1 2 3 3 4 5 5 5 6 9]

# Dizideki 5'den büyük elemanları filtrele
c = a[a > 5]
print(c)  # Output: [9 6]


[1 1 2 3 3 4 5 5 5 6 9]
[9 6]


## - Dizilerde İndeksleme ve Dilimleme

### Dizi elemanlarına erişim ve değiştirme

- **İndeksleme:** Dizi elemanlarına erişmek veya değiştirmek için dizinin indis numarasını kullanabiliriz. İndeksleme sıfırdan başladığı için ilk elemanın indisi 0'dır.

In [42]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

# Dizi elemanlarına erişmek
print(arr[0]) # 1
print(arr[2]) # 3

# Dizi elemanını değiştirmek 
arr[1] = 6
print(arr) # [1 6 3 4 5]

1
3
[1 6 3 4 5]


- **Dilimleme: Dilimleme (slicing):** NumPy dizisinde bir aralık belirleyerek alt küme oluşturmamıza olanak tanır. Aşağıdaki örnekte, bir dizi üzerindeki ikinci ve dördüncü elemanları seçiyoruz.

In [43]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
print(arr[1:4]) # [2 3 4]

arr[1:4] = np.array([6, 7, 8])
print(arr) # [1 6 7 8 5]

[2 3 4]
[1 6 7 8 5]


- **Maskeleme :** Bir dizi üzerinde belirli bir koşulu sağlayan elemanları seçmemize olanak tanır. Koşul, bir dizi ile aynı şekle sahip bir bool dizisi olmalıdır. Aşağıdaki örnekte, 3'ten büyük olan elemanları seçiyoruz.

In [44]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
mask = arr > 3
print(mask) # [False False False  True  True]

print(arr[mask]) # [4 5]

arr[mask] = np.array([9, 10])
print(arr) # [1 2 3 9 10]


[False False False  True  True]
[4 5]
[ 1  2  3  9 10]


- **Fancy indeksleme:** Fancy indeksleme, bir NumPy dizisi üzerinde birden fazla elemanın seçilmesine olanak tanır. Bu işlem için bir indeks listesi kullanılır. Aşağıdaki örnekte, bir dizi üzerindeki 0., 2. ve 4. elemanları seçiyoruz.

In [45]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
indices = [0, 2, 4]
print(arr[indices]) # [1 3 5]

arr[indices] = np.array([6, 7, 8])
print(arr) # [6 2 7 4 8]

[1 3 5]
[6 2 7 4 8]


### İndeksleme ve dilimleme işlemlerinin uygulanması

İndeksleme ve dilimleme işlemleri, bir dizinin belli bir elemanına erişmek veya bir alt dizisini seçmek için kullanılan işlemlerdir.

İndeksleme işlemi, bir dizinin belli bir elemanına doğrudan erişmek için kullanılır. Dizi elemanlarına sıfırdan başlayan bir indeks numarası verilir ve bu indeks numarası kullanılarak elemana erişilir.

Dilimleme işlemi ise, bir dizinin bir alt dizisini seçmek için kullanılır. Dilimleme işlemi için bir başlangıç ve bir bitiş indeksi belirlenir ve belirlenen indeksler arasındaki elemanlar seçilir. Bu işlemle, dizinin bir alt kümesi oluşturulur.

In [46]:
import numpy as np

# 1D dizi oluşturma
arr = np.array([1, 2, 3, 4, 5])

# Birinci elemana erişim
print(arr[0])  # Output: 1

# Son elemana erişim
print(arr[-1])  # Output: 5

# İkinci ve üçüncü elemanlara erişim
print(arr[1:3])  # Output: [2, 3]

# Dizinin başlangıcından üçüncü elemana kadar erişim
print(arr[:3])  # Output: [1, 2, 3]

# Dördüncü elemandan dizinin sonuna kadar erişim
print(arr[3:])  # Output: [4, 5]

# 2D dizi oluşturma
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# İlk satıra erişim
print(arr2d[0])  # Output: [1, 2, 3]

# İkinci satırın üçüncü elemanına erişim
print(arr2d[1, 2])  # Output: 6

# İlk iki satır ve son iki sütuna erişim
print(arr2d[:2, 1:])  # Output: [[2, 3], [5, 6]]


1
5
[2 3]
[1 2 3]
[4 5]
[1 2 3]
6
[[2 3]
 [5 6]]


Yukarıdaki örnekler, 1D ve 2D NumPy dizilerinin farklı elemanlarına nasıl erişileceğini ve dilimleneceğini göstermektedir. NumPy dizileri, dilimleme işlemlerinde oldukça esnektir ve ileri düzey indeksleme yöntemleriyle birlikte kullanıldığında, veri manipülasyonu ve analizinde oldukça güçlü bir araçtır.

### İndeksleme ve dilimleme için örnekler

In [48]:
import numpy as np

# 3x4 boyutunda bir numpy dizisi oluşturalım
arr = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12]])

# İndeksleme örneği
print(arr[0, 0])  # 1
print(arr[1, 2])  # 7
print(arr[2, -1])  # 12

# Dilimleme örneği
print(arr[0, 1:3])  # [2 3]
print(arr[:, 2])  # [ 3  7 11]
print(arr[1:, 1:3])  # [[ 6  7]
                     #  [10 11]]

# Dilimleme ile eleman değiştirme örneği
arr[:, 2] = [13, 14, 15]  # 3. sütunu [13, 14, 15] ile değiştirir
print(arr)

# Yeni bir dizi oluşturma örneği
new_arr = arr[:, 1:3].copy()  # [2 3], [6 7], [10 11] elemanlarını içeren yeni bir dizi oluşturur
print(new_arr)


1
7
12
[2 3]
[ 3  7 11]
[[ 6  7]
 [10 11]]
[[ 1  2 13  4]
 [ 5  6 14  8]
 [ 9 10 15 12]]
[[ 2 13]
 [ 6 14]
 [10 15]]


### - Makine öğrenmesi için NumPy ile veri manipülasyonu ve dönüştürme işlemleri.

Makine öğrenmesi için NumPy, veri manipülasyonu ve dönüştürme işlemlerini kolayca yapmamızı sağlar. Veri manipülasyonu, veri setlerindeki bilgileri düzenlemek, dönüştürmek, birleştirmek ve temizlemek gibi işlemleri içerir. Bu işlemler genellikle, veri setlerini makine öğrenmesi modellerine uygun hale getirmek için yapılır.

NumPy, çok boyutlu dizileri kullanarak veri manipülasyonunu kolaylaştırır. Veri setleri, NumPy dizileri olarak temsil edilebilir ve bu diziler üzerinde işlemler yapılabilir. Örneğin, veri setindeki her bir özellik bir NumPy dizisi olarak temsil edilebilir.

Veri dönüştürme işlemleri, veri setlerinin makine öğrenmesi modellerine uygun hale getirilmesini sağlar. Örneğin, kategorik verilerin sayısal verilere dönüştürülmesi veya veri setlerinin normalleştirilmesi gibi işlemler veri dönüştürme işlemlerine örnek olarak verilebilir.

NumPy, veri manipülasyonu ve dönüştürme işlemlerinde çeşitli fonksiyonlar ve yöntemler sağlar. Bunlar arasında;

- **reshape:** Bir dizinin boyutunu değiştirmek için kullanılır. Örneğin, 1 boyutlu bir diziyi 2 boyutlu bir diziye dönüştürmek isterseniz, kullanabilirsiniz.
- **concatenate:** İki veya daha fazla diziyi birleştirmek için kullanılır. axis parametresi ile birleştirme yönü belirtilebilir.
- **split:** Bir diziyi parçalara ayırmak için kullanılır. split fonksiyonu, bölünecek diziyi ve bölünme noktalarının dizisini alır. Örneğin, bir diziyi üç parçaya ayırmak için [n1, n2] gibi - bir bölünme noktası dizisi kullanabilirsiniz.
- **transpose:** Bir dizinin transpozunu almak için kullanılır. Yani, bir matrisin satırlarını sütunlarına ve sütunlarını satırlarına dönüştürür.
- **flatten:** Bir dizinin tüm elemanlarını tek boyutlu hale getirmek için kullanılır.
- **ravel:** flatten işlevi ile aynı işi yapar, ancak orijinal diziye yapılan değişikliklerin daha olası olduğu bir görünüm döndürür.
- **unique:** Tekrar eden elemanları bir dizi içerisinden çıkarmak için kullanılır.
- **isnan:** NaN (Not a Number) değerleri içeren bir dizi içindeki NaN değerlerinin yerini belirlemek için kullanılır.
- **argmax:** Bir dizideki en büyük elemanın indisini döndürür.
- **argmin:** Bir dizideki en küçük elemanın indisini döndürür.
- **where:** Koşula uyan elemanların yerine belirli bir değeri atamak için kullanılır.
- **clip:** Bir dizideki değerleri, belirli bir aralıkta sınırlamak için kullanılır.
- **mean:** Bir dizinin aritmetik ortalamasını hesaplar.
- **std:** Bir dizinin standart sapmasını hesaplar.
- **min:** Bir dizinin en küçük elemanını döndürür.
- **max:** Bir dizinin en büyük elemanını döndürür.
- **median:** Bir dizinin ortanca elemanını döndürür. 
gibi fonksiyonlar yer alır. Bu fonksiyonlar, veri setlerini manipüle etmek ve dönüştürmek için kullanılabilir.

In [9]:
import numpy as np

# reshape
arr1 = np.array([1, 2, 3, 4, 5, 6])
arr2 = arr1.reshape((2, 3))
print("Reshaped Array:")
print(arr2)

# concatenate
arr3 = np.array([[1, 2], [3, 4]])
arr4 = np.array([[5, 6], [7, 8]])
arr5 = np.concatenate((arr3, arr4), axis=1)
print("Concatenated Array:")
print(arr5)

# split
arr6 = np.array([1, 2, 3, 4, 5, 6])
arr7, arr8 = np.split(arr6, [3])
print("Split Arrays:")
print(arr7)
print(arr8)

# transpose
arr9 = np.array([[1, 2], [3, 4], [5, 6]])
arr10 = np.transpose(arr9)
print("Transposed Array:")
print(arr10)

# flatten and ravel
arr11 = np.array([[1, 2], [3, 4]])
arr12 = np.array([[5, 6], [7, 8]])
arr13 = np.concatenate((arr11, arr12), axis=1)
arr14 = np.ravel(arr13)
arr15 = arr13.flatten()
print("Flattened and Raveled Arrays:")
print(arr14)
print(arr15)

# unique
arr16 = np.array([1, 2, 2, 3, 4, 4, 4, 5, 5])
arr17 = np.unique(arr16)
print("Unique Values:")
print(arr17)

# isnan
arr18 = np.array([1, 2, np.nan, 4, 5])
arr19 = np.isnan(arr18)
print("Is NaN:")
print(arr19)

# argmax and argmin
arr20 = np.array([1, 4, 2, 8, 3, 9])
arr21 = np.argmax(arr20)
arr22 = np.argmin(arr20)
print("Argmax and Argmin:")
print(arr21)
print(arr22)

# where
arr23 = np.array([1, 2, 3, 4, 5])
arr24 = np.where(arr23 < 3, 0, arr23)
print("Where:")
print(arr24)

# clip
arr25 = np.array([1, 2, 3, 4, 5])
arr26 = np.clip(arr25, 2, 4)
print("Clipped:")
print(arr26)

# mean, std, min, max, and median
arr27 = np.array([1, 2, 3, 4, 5])
mean = np.mean(arr27)
std = np.std(arr27)
min_val = np.min(arr27)
max_val = np.max(arr27)
median = np.median(arr27)
print("Mean, Standard Deviation, Min, Max, and Median:")
print(mean)
print(std)
print(min_val)
print(max_val)
print(median)


Reshaped Array:
[[1 2 3]
 [4 5 6]]
Concatenated Array:
[[1 2 5 6]
 [3 4 7 8]]
Split Arrays:
[1 2 3]
[4 5 6]
Transposed Array:
[[1 3 5]
 [2 4 6]]
Flattened and Raveled Arrays:
[1 2 5 6 3 4 7 8]
[1 2 5 6 3 4 7 8]
Unique Values:
[1 2 3 4 5]
Is NaN:
[False False  True False False]
Argmax and Argmin:
5
0
Where:
[0 0 3 4 5]
Clipped:
[2 2 3 4 4]
Mean, Standard Deviation, Min, Max, and Median:
3.0
1.4142135623730951
1
5
3.0


In [2]:
#!pip install numpy
import numpy as np

### NumPy Dizileri (array) Oluşturma:

In [4]:
a = np.array([1,2,3,4,5,6])
print(a)
print(type(a))

# 1D dizi oluşturma
arr_1d = np.array([1, 2, 3, 4, 5])

print(arr_1d)

# 2D dizi oluşturma
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])

print(arr_2d)

[1 2 3 4 5 6]
<class 'numpy.ndarray'>
[1 2 3 4 5]
[[1 2 3]
 [4 5 6]]


In [13]:
b = np.array([3.14, 5, 6, 7, 8, 9.3265], dtype=int)
print(b)
c = np.array([3.14, 5, 6, 7, 8, 9.3265], dtype="float32")
print(c)

[3 5 6 7 8 9]
[3.14   5.     6.     7.     8.     9.3265]


### Sıfırdan Array oluşturmak
NumPy kütüphanesi ile bir dizi veya matris oluşturmak oldukça kolaydır. Yeni bir NumPy dizisi oluşturmak için numpy.array() fonksiyonunu kullanabilirsiniz. Aşağıda birkaç örnek gösterilmiştir:

In [14]:
import numpy as np

# Sıfırlardan oluşan bir 1D dizi oluşturun
zeros = np.zeros(5)
print(zeros)  # [0. 0. 0. 0. 0.]

# Birlerden oluşan bir 1D dizi oluşturun
ones = np.ones(3)
print(ones)  # [1. 1. 1.]

# Belirtilen bir şekle sahip sıfırlardan oluşan bir dizi oluşturun
zeros_2d = np.zeros((2, 3))
print(zeros_2d)  
# [[0. 0. 0.]
#  [0. 0. 0.]]

# Belirtilen bir şekle sahip rastgele sayılardan oluşan bir dizi oluşturun
random = np.random.rand(2, 3)
print(random)
# [[0.7840484  0.25539245 0.41152297]
#  [0.36973662 0.45695694 0.16317017]]

[0. 0. 0. 0. 0.]
[1. 1. 1.]
[[0. 0. 0.]
 [0. 0. 0.]]
[[0.71680256 0.73300518 0.32204628]
 [0.29546463 0.52924008 0.17507908]]


------------------------------------------------------

np.zeros((2, 3)) ifadesindeki '(2, 3)' tuple (demet) olup, bir NumPy dizisinin boyutlarını belirtir. Bu tuple içindeki ilk eleman dizi boyutunun birinci boyutunu, ikinci eleman ise dizi boyutunun ikinci boyutunu belirtir.

Yani, np.zeros((2, 3)) kodu ile iki satır ve üç sütundan oluşan, tüm elemanları sıfır olan bir 2 boyutlu dizi oluşturulur. np.zeros((3, 4)) kodu ile ise üç satır ve dört sütundan oluşan, tüm elemanları sıfır olan başka bir 2 boyutlu dizi oluşturulabilir. Benzer şekilde, np.ones((2, 2, 2)) ile 2x2x2 boyutlarında, tüm elemanları 1 olan bir 3 boyutlu dizi oluşturulabilir.

### NumPy Dizileri İşleme:

NumPy, dizileri işlemek için birçok özellik sağlar. Bu bölümde, dizilerin indekslenmesi, kesilmesi, yeniden şekillendirilmesi, birleştirilmesi vb. konular ele alınır. Örneğin:

In [8]:
# Dizi elemanlarına erişim
arr = np.array([1, 2, 3, 4, 5])
print(arr[0])  # 1
print(arr[1:3])  # [2, 3]

# Boyutlu dizilere erişim
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print(arr[0, 1]) # 2
print(arr[1, 1:3]) # [7 8]

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(arr[0, 1, 2]) # 6

# Dizi yeniden şekillendirme
arr = np.array([1, 2, 3, 4, 5, 6])
new_arr = arr.reshape(2, 3)
print(new_arr)
# [[1 2 3]
#  [4 5 6]]

# Dizi birleştirme
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
new_arr = np.concatenate((arr1, arr2))
print(new_arr)  # [1 2 3 4 5 6]

1
[2 3]
2
[7 8]
6
[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]


### NumPy Dizileri Matematiksel İşlemler:

In [21]:
# Toplama, Çıkarma, Çarpma, Bölme
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
print(arr1 + arr2)  # [5 7 9]
print(arr1 - arr2)  # [-3 -3 -3]
print(arr1 * arr2)  # [ 4 10 18]
print(arr1 / arr2)  # [0.25 0.4  0.5 ]

# Karekök
x = np.array([4, 9, 16])
karekok = np.sqrt(x)
print(karekok)  # Output: [2. 3. 4.]

# Logaritma
arr = np.array([1, 2, 3])
print(np.log(arr))  # [0.         0.69314718 1.09861229]

# Üs alma
arr = np.array([1, 2, 3])
print(np.power(arr, 2))  # [1 4 9]

# Trigonometrik fonksiyonlar
arr = np.array([0, 30, 45, 60, 90])
print(np.sin(np.radians(arr)))  # [0.         0.5        0.70710678 0.8660254  1.        ]

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]
[2. 3. 4.]
[0.         0.69314718 1.09861229]
[1 4 9]
[0.         0.5        0.70710678 0.8660254  1.        ]


### NumPy Dizileri İndeksleme ve Kesme:

NumPy dizileri, indeksleme ve kesme işlemleri için özelleştirilmiş bir arayüz sağlar. Bu bölümde, dizilerin belirli elemanlara nasıl erişileceği, belli bir aralıktaki elemanların nasıl seçileceği vb. konular ele alınır. Örneğin:


In [23]:
# Dizi elemanlarına erişim
arr = np.array([1, 2, 3, 4, 5])
print(arr[0])  # 1
print(arr[1:3])  # [2, 3]

# 2D Dizi elemanlarına erişim
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr[0, 1])  # 2
print(arr[1:, 1:])  # [[5 6][8 9]]

1
[2 3]
2
[[5 6]
 [8 9]]


### NumPy Dizileri Birleştirme ve Yeniden Şekillendirme

NumPy, dizileri birleştirme ve yeniden şekillendirme işlemleri için özelleştirilmiş bir arayüz sağlar. Bu bölümde, dizilerin nasıl birleştirileceği ve yeniden şekillendirileceği konuları ele alınır. Örneğin:


In [24]:
# Dizi birleştirme
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
new_arr = np.concatenate((arr1, arr2))
print(new_arr)  # [1 2 3 4 5 6]

# Yığınlar halindeki 2D dizileri birleştirme
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])
new_arr = np.concatenate((arr1, arr2), axis=1)
print(new_arr)
# [[1 2 5 6]
#  [3 4 7 8]]

# Yeniden şekillendirme
arr = np.array([1, 2, 3, 4, 5, 6])
new_arr = arr.reshape(2, 3)
print(new_arr)
# [[1 2 3]
#  [4 5 6]]


[1 2 3 4 5 6]
[[1 2 5 6]
 [3 4 7 8]]
[[1 2 3]
 [4 5 6]]


### NumPy Dizileri İstatistiksel İşlemler: 
NumPy, diziler üzerinde birçok istatistiksel işlem yapabilir. Bu bölümde, diziler üzerinde ortalama, medyan, varyans gibi istatistiksel işlemlerin nasıl yapılacağı anlatılır. Örneğin:

In [25]:
# Ortalama
arr = np.array([1, 2, 3, 4, 5])
print(np.mean(arr))  # 3.0

# Medyan
arr = np.array([1, 2, 3, 4, 5])
print(np.median(arr))  # 3.0

# Varyans
arr = np.array([1, 2, 3, 4, 5])
print(np.var(arr))  # 2.0

# Standart sapma
arr = np.array([1, 2, 3, 4, 5])
print(np.std(arr))  # 1.41421356

3.0
3.0
2.0
1.4142135623730951


### NumPy Dizileri Dosya İşlemleri

NumPy, dizilerin dosya işlemleri yapmak için kullanılabilmesine olanak sağlar. Bu bölümde, NumPy dizilerinin nasıl dosyaya yazılacağı ve dosyadan nasıl okunacağı konuları ele alınır. Örneğin:

In [ ]:
# Dizi dosyaya yazma
arr = np.array([1, 2, 3, 4, 5])
np.savetxt('array.txt', arr)

# Dizi dosyadan okuma
arr = np.loadtxt('array.txt')
print(arr)  # [1. 2. 3. 4. 5.]

[1. 2. 3. 4. 5.]


### transpose()

"Transpose", matrislerin veya tabloların sütunlarını satırlara ve satırları sütunlara dönüştürmek için kullanılan bir matematiksel işlemdir. Transpoze alma işlemi, matrisin satırlarının sütunlarına, sütunlarının ise satırlarına dönüştürülmesini sağlar.

Örneğin, 3x2 boyutunda bir matrisimiz olsun. Bu matrisin transpozesi, 2x3 boyutunda bir matris olacaktır.


In [2]:
import numpy as np

a = np.array([[1, 2], [3, 4], [5, 6]])
a_transpose = np.transpose(a)
print(a_transpose)

[[1 3 5]
 [2 4 6]]


# Örnek Uygulama - 1

In [10]:
import numpy as np

# Günlük yaşamdan bir örnek veri seti oluşturalım
gunluk_adim_sayisi = [2343, 3421, 3421, 4392, 4321, 3421, 3421]
gunluk_kalori_tuketimi = [1900, 2000, 1800, 2200, 2100, 2000, 1900]

# Numpy array'leri oluşturalım
adim_array = np.array(gunluk_adim_sayisi)
kalori_array = np.array(gunluk_kalori_tuketimi)

# Array boyutlarını görelim
print("Adım array boyutu:", adim_array.shape)
print("Kalori array boyutu:", kalori_array.shape)

# Array'ler üzerinde bazı matematiksel işlemler yapalım
ortalama_adim = np.mean(adim_array)
ortalama_kalori = np.mean(kalori_array)

print("Ortalama adım sayısı:", ortalama_adim)
print("Ortalama kalori tüketimi:", ortalama_kalori)

en_fazla_adim = np.max(adim_array)
en_fazla_kalori = np.max(kalori_array)

print("En fazla adım sayısı:", en_fazla_adim)
print("En fazla kalori tüketimi:", en_fazla_kalori)

# Array'ler arasında matematiksel işlemler yapalım
adim_kalori_orani = adim_array / kalori_array
print("Adım/Kalori oranı:", adim_kalori_orani)

# Array'leri birleştirelim
gun_array = np.column_stack((adim_array, kalori_array))
print("Günlük adım ve kalori sayıları:")
print(gun_array)

Adım array boyutu: (7,)
Kalori array boyutu: (7,)
Ortalama adım sayısı: 3534.285714285714
Ortalama kalori tüketimi: 1985.7142857142858
En fazla adım sayısı: 4392
En fazla kalori tüketimi: 2200
Adım/Kalori oranı: [1.23315789 1.7105     1.90055556 1.99636364 2.05761905 1.7105
 1.80052632]
Günlük adım ve kalori sayıları:
[[2343 1900]
 [3421 2000]
 [3421 1800]
 [4392 2200]
 [4321 2100]
 [3421 2000]
 [3421 1900]]


## 1. Veri Okuma ve Yükleme:

# Örnek Uygulama - 2

In [13]:
import numpy as np

# Öğrenci notlarından oluşan bir veri seti oluşturalım
notlar = [[80, 70, 90, 60],
          [85, 75, 95, 65],
          [90, 80, 100, 70],
          [75, 65, 85, 55]]

# Numpy array'ine dönüştürelim
notlar_array = np.array(notlar)

# Array üzerinde bazı işlemler yapalım
# axis=0, bir çok boyutlu array'in sütunlar boyunca işlem yapılmasını ifade eder.
sinav_ortalamalari = np.mean(notlar_array, axis=0)
print("Sınav ortalamaları:", sinav_ortalamalari)

# axis=1, bir çok boyutlu array'in satırlar boyunca işlem yapılmasını ifade eder.  
ogrenci_ortalamalari = np.mean(notlar_array, axis=1)
print("Öğrenci ortalamaları:", ogrenci_ortalamalari)

en_yuksek_notlar = np.max(notlar_array, axis=0)
print("En yüksek notlar:", en_yuksek_notlar)

en_yuksek_notlarin_alindigi_dersler = np.argmax(notlar_array, axis=1)
print("En yüksek notların alındığı dersler:", en_yuksek_notlarin_alindigi_dersler)

# Array'leri birleştirelim
final_notlari = np.array([85, 90, 92, 78])
notlar_array = np.vstack((notlar_array, final_notlari))
print("Tüm notlar:")
print(notlar_array)

# Boolean index ile bazı işlemler yapalım
gecti_mi = notlar_array >= 70
print("Geçti mi?", gecti_mi)

kac_tane_70_ustu = np.sum(gecti_mi)
print("70 ve üstü not alan öğrenci sayısı:", kac_tane_70_ustu)

en_az_3_70_ustu = np.sum(gecti_mi, axis=1) >= 3
print("En az 3 dersten 70 ve üstü alan öğrenciler:", en_az_3_70_ustu)

Sınav ortalamaları: [82.5 72.5 92.5 62.5]
Öğrenci ortalamaları: [75. 80. 85. 70.]
En yüksek notlar: [ 90  80 100  70]
En yüksek notların alındığı dersler: [2 2 2 2]
Tüm notlar:
[[ 80  70  90  60]
 [ 85  75  95  65]
 [ 90  80 100  70]
 [ 75  65  85  55]
 [ 85  90  92  78]]
Geçti mi? [[ True  True  True False]
 [ True  True  True False]
 [ True  True  True  True]
 [ True False  True False]
 [ True  True  True  True]]
70 ve üstü not alan öğrenci sayısı: 16
En az 3 dersten 70 ve üstü alan öğrenciler: [ True  True  True False  True]
